name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      #build docker images
    - name: Build Docker images
      run: docker compose build

      #run trivy scans for image
    - name: Run Trivy vulnerability scanner on entitlement-server
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'local-testbed-entitlement-server'
        format: 'table'
        exit-code: '0' 
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy vulnerability scanner on operator-adapter
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'local-testbed-operator-adapter'
        format: 'table'
        exit-code: '0' 
        severity: 'CRITICAL,HIGH,MEDIUM'

      #start services
    - name: Start services
      run: docker compose up -d

    - name: Run smoke tests
      run: make smoke

    - name: Stop services
      run: docker compose down